title: Hummingbird Sanctuary
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0
  brandStrength: 0
  lightness: 0.8387097
  brandColors:
    - '#FFFFFF'
    - '#7195E1'
    - '#121315'
    - '#B4BC71'
    - '#AC4864'
  rhythmicContrast: 0.516129
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: JDubsWorld
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.85426
layout_spectrum: 1
