name: JDubsWorld
favicon: null
layout_spectrum: 0.8806500369682908
typography_spectrum: 0.85426
title: Hummingbird Sanctuary
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.006373458541929722
  rhythmicContrast: 0.33256401121616364
purpose: []
